<script lang="ts">
	import { CodeBlock, TextLink } from "$pkg/ui/elements/index";

	const sampleCode = `<EntryOrderConfig
  bind:layout={actualLayout}
  bind:orderUrl={orderUrl}
  allEntries={entryList}
/>`;

	const propSources = import.meta.glob("/src/lib/ui/elements/CodeBlock/CodeBlockProps.ts", {
		query: "?raw",
		import: "default",
		eager: true
	});
	const propsCode = propSources["/src/lib/ui/elements/CodeBlock/CodeBlockProps.ts"] as string ?? "";

	const basicUsage = `<script lang="ts">
import { CodeBlock } from "@turnipxenon/pineapple/elements";
<\/script>

<CodeBlock
  code={\`<EntryOrderConfig
  bind:layout={actualLayout}
  bind:orderUrl={orderUrl}
  allEntries={entryList}
/>\`}
  lang="ts"
  classes="max-w-2xl"
/>`;

	const styledUsage = `<script lang="ts">
import { CodeBlock } from "@turnipxenon/pineapple/elements";
<\/script>

<CodeBlock
  code={\`console.log("Hello from pineapple");\`}
  lang="js"
  classes="max-w-xl border border-slate-300/70"
  prePadding="[&>pre]:p-6"
  preClasses="[&>pre]:text-sm"
/>`;
</script>

<h1>Code block</h1>

<h2>About</h2>
<p>Display formatted code with syntax highlighting, light/dark themes, and a copy button.</p>

<h2>Features</h2>
<ul>
	<li>Syntax highlighting powered by Shiki. See <TextLink href="https://shiki.style/">https://shiki.style/</TextLink> and
		<TextLink href="https://www.skeleton.dev/docs/integrations/code-block/svelte/">https://www.skeleton.dev/docs/integrations/code-block/svelte/</TextLink></li>
	<li>Light and dark theme pairing using Catppuccin palettes.</li>
	<li>Copy button for quick clipboard access.</li>
	<li>Wrapper and pre-element styling hooks for layout control.</li>
</ul>

<h2>Sample</h2>

<CodeBlock code={sampleCode} lang="svelte" classes="max-w-2xl" />


<h2>Usage</h2>

<p><b>Basic usage:</b></p>
<CodeBlock code={basicUsage} lang="svelte" classes="max-w-2xl" />

<p><b>Custom styling:</b></p>
<CodeBlock code={styledUsage} lang="svelte" classes="max-w-2xl" />

<p><b>transformerNotationDiff (see <TextLink href="https://shiki.style/packages/transformers#transformernotationdiff">https://shiki.style/packages/transformers#transformernotationdiff</TextLink>):</b></p>
<CodeBlock
	code={`@import 'tailwindcss'; /*[!code --]*/
@import "@skeletonlabs/skeleton"; /*[!code --]*/
@import "@skeletonlabs/skeleton/optional/presets"; /*[!code ++]*/
@import "@skeletonlabs/skeleton/themes/legacy"; /*[!code ++]*/
@import '../../../node_modules/@turnipxenon/pineapple/dist/styles/tailwind.css';
@import '../../../node_modules/@turnipxenon/pineapple/dist/styles/color-tokens.css';`}
	lang="css"
	classes="max-w-2xl"
/>

<CodeBlock
	code={`<!--source code for above-->

<CodeBlock
\tcode={\`@import 'tailwindcss'; /*[!code --]*/
@import "@skeletonlabs/skeleton"; /*[!code --]*/
@import "@skeletonlabs/skeleton/optional/presets"; /*[!code ++]*/
@import "@skeletonlabs/skeleton/themes/legacy"; /*[!code ++]*/
@import '../../../node_modules/@turnipxenon/pineapple/dist/styles/tailwind.css';
@import '../../../node_modules/@turnipxenon/pineapple/dist/styles/color-tokens.css';\`}
\tlang="css"
\tclasses="max-w-2xl"
/>`}
	lang="svelte"
	classes="max-w-2xl"
/>

<h2>Props</h2>
<CodeBlock code={propsCode} lang="ts" classes="max-w-2xl" />

<h2>Notes</h2>
<ul>
	<li>If styling is broken, there's most likely something wrong with the code props. Common issues include <b>having an unopened comment section like <code>/*[!code ++]</code></b></li>
	<li>We had Tailwind at the time this was made but there's too much effort to remove it completely.</li>
	<li>Highlighted output is generated by Shiki at render time.</li>
	<li>The copy button appears inside the highlighted block and resets after a short delay.</li>
	<li>Use <code>prePadding</code> or <code>preClasses</code> to adjust spacing and typography.</li>
</ul>

<p>Source code:
	<TextLink target="_blank" href="https://github.com/TurnipXenon/pineapple/blob/2802a54370bd643004f0b4d5d40431b476e1b5f2/src/lib/ui/elements/CodeBlock/CodeBlock.svelte">https://github.com/TurnipXenon/pineapple/blob/2802a54370bd643004f0b4d5d40431b476e1b5f2/src/lib/ui/elements/CodeBlock/CodeBlock.svelte</TextLink>
</p>
<p>Example code:
	<TextLink target="_blank" href="https://github.com/TurnipXenon/pineapple/blob/70a3193488d345e609b9151f27f17511650bb12f/src/lib/ui/templates/SeaweedLayout/SeaweedLayout.svelte#L248">https://github.com/TurnipXenon/pineapple/blob/70a3193488d345e609b9151f27f17511650bb12f/src/lib/ui/templates/SeaweedLayout/SeaweedLayout.svelte#L248</TextLink>
</p>
