<script lang="ts">
	import { CodeBlock, TextLink } from "$pkg/ui/elements/index";

	const sampleCode = `<EntryOrderConfig
  bind:layout={actualLayout}
  bind:orderUrl={orderUrl}
  allEntries={entryList}
/>`;

	const propSources = import.meta.glob("/src/lib/ui/elements/CodeBlock/CodeBlockProps.ts", {
		query: "?raw",
		import: "default",
		eager: true
	});
	const propsCode = propSources["/src/lib/ui/elements/CodeBlock/CodeBlockProps.ts"] ?? "";

	const basicUsage = `<CodeBlock
  code={\`<EntryOrderConfig
  bind:layout={actualLayout}
  bind:orderUrl={orderUrl}
  allEntries={entryList}
/>\`}
  lang="ts"
  classes="max-w-2xl"
/>`;

	const styledUsage = `<CodeBlock
  code={\`console.log("Hello from pineapple");\`}
  lang="js"
  classes="max-w-xl border border-slate-300/70"
  prePadding="[&>pre]:p-6"
  preClasses="[&>pre]:text-sm"
/>`;
</script>

<h1>Code block</h1>

<h2>About</h2>
<p>Display formatted code with syntax highlighting, light/dark themes, and a copy button.</p>

<h2>Features</h2>
<ul>
	<li>Syntax highlighting powered by Shiki.</li>
	<li>Light and dark theme pairing using Catppuccin palettes.</li>
	<li>Copy button for quick clipboard access.</li>
	<li>Wrapper and pre-element styling hooks for layout control.</li>
</ul>

<h2>Sample</h2>

<CodeBlock code={sampleCode} lang="ts" classes="max-w-2xl" />


<h2>Usage</h2>

<p><b>Basic usage:</b></p>
<CodeBlock code={basicUsage} lang="ts" classes="max-w-2xl" />

<p><b>Custom styling:</b></p>
<CodeBlock code={styledUsage} lang="ts" classes="max-w-2xl" />

<h2>Props</h2>
<CodeBlock code={propsCode} lang="ts" classes="max-w-2xl" />

<h2>Notes</h2>
<ul>
	<li>We had Tailwind at the time this was made but there's too much effort to remove it completely. New</li>
	<li>Highlighted output is generated by Shiki at render time.</li>
	<li>The copy button appears inside the highlighted block and resets after a short delay.</li>
	<li>Use <code>prePadding</code> or <code>preClasses</code> to adjust spacing and typography.</li>
</ul>

<p>Source code:
	<TextLink target="_blank" href="https://github.com/TurnipXenon/pineapple/blob/2802a54370bd643004f0b4d5d40431b476e1b5f2/src/lib/ui/elements/CodeBlock/CodeBlock.svelte">https://github.com/TurnipXenon/pineapple/blob/2802a54370bd643004f0b4d5d40431b476e1b5f2/src/lib/ui/elements/CodeBlock/CodeBlock.svelte</TextLink>
</p>
<p>Example code:
	<TextLink target="_blank" href="https://github.com/TurnipXenon/pineapple/blob/70a3193488d345e609b9151f27f17511650bb12f/src/lib/ui/templates/SeaweedLayout/SeaweedLayout.svelte#L248">https://github.com/TurnipXenon/pineapple/blob/70a3193488d345e609b9151f27f17511650bb12f/src/lib/ui/templates/SeaweedLayout/SeaweedLayout.svelte#L248</TextLink>
</p>
